#!/bin/sh

BUSYBOX=busybox-1.38.0

echo Building BusyBox

tar xfj $BUSYBOX.tar.bz2 &&
ln -fs $BUSYBOX busybox &&
{
    arch=$(uname -m)

	cp -av .config busybox/.config

} &&
cd busybox && make -j $(($(nproc) + 1)) && make install
